### PR TITLE
Bugfix/change updates

### LINKED ISSUE #5: Not handling updates from Facebook Webhooks
The `MessageQuickly::CallbackParser` fails to handle updates sent from Facebook as described in
https://developers.facebook.com/docs/graph-api/webhooks#receiveupdates.

An identified form of an update message from Facebook is:

```
{
  "entry"=>[
      {
        "changes"=>[
            { 
              "field"=>"conversations", 
              "value"=>{
                "thread_id"=>"t_mid.1234567890123:123456789012345678", 
                "page_id"=>123456789012345
              } 
            }
          ], 
        "id"=>"123456789012345", 
        "time"=>1476077449
      }
    ],
  "object"=>"page"
}
```

The above causes `MessageQuickly::CallbackParser#parse` to break.

### PR DESCRIPTION
**Pull request by Wei-LiangChew**
Fix #5 Not handling updates from Facebook Webhooks.

This PR resolves the above issue by implementing the `ChangeUpdateEvent` and integrating it with the `MessageQuickly::CallbackParser` to handle the change updates.

Note: I couldn't figure out how the `spec/dummy` plays into the specs, so I'm not sure the integration is fully tested, although I did add the new event handling into the specs for `MessageQuickly::CallbackParser`

### CODE REVIEW

File: spec/controllers/webhooks_controller_spec.rb [hunk 1]
```diff
@@ -124,6 +124,23 @@
 
     end
 
+    context 'with a change update event' do
+
+      let(:optin_json) { File.read("spec/fixtures/change_notification_request.json") }
+
+      context 'with valid params' do
+        before { post :callback, optin_json }
+        it { expect(response).to have_http_status(200) }
```
Comment (Drenmi) [inline spec/controllers/webhooks_controller_spec.rb:133]: I like to use the symbolic names for statuses:

```
have_http_status(:success)
```

etc.

File: spec/controllers/webhooks_controller_spec.rb [hunk 2]
```diff
@@ -124,6 +124,23 @@
 
     end
 
+    context 'with a change update event' do
+
+      let(:optin_json) { File.read("spec/fixtures/change_notification_request.json") }
```
Comment (Drenmi) [inline spec/controllers/webhooks_controller_spec.rb:129]: This string literal uses double quotes, while the rest don't.

File: lib/message_quickly/callback_parser.rb [hunk 3]
```diff
@@ -55,9 +56,13 @@ def initialize(json)
     def parse
       events = []
       process_entry_json(@json['entry']) do |params|
-        WEBHOOK_LOOKUP.keys.each do |key|
-          if params[:messaging][key]
-            events << WEBHOOK_LOOKUP[key].new(params[:messaging])
+        if params[:changes].present?
```
Comment (Drenmi) [inline lib/message_quickly/callback_parser.rb:59]: This could potentially be:

```
if params.dig(:changes)
```

but since we already have a dependency on Rails, I don't mind using the ActiveSupport methods, as the intent reads clearer.

**Review by Drenmi — APPROVED** [review]
LGTM! 🚀

File: spec/controllers/webhooks_controller_spec.rb (hunk 1 above)
Comment (Wei-LiangChew) [reply spec/controllers/webhooks_controller_spec.rb:133]: Yeah, I stuck to this because it seemed to be the convention used in the specs already ><

File: spec/controllers/webhooks_controller_spec.rb (hunk 2 above)
Comment (Wei-LiangChew) [reply spec/controllers/webhooks_controller_spec.rb:129]: Right. There's this strange convention throughout the spec file where file name strings are defined with double quotes

**Comment by Drenmi** [comment]
Let's merge this. 😀 

🚀

**Comment by Wei-LiangChew** [comment]
Right sorry, I forgot 😅
